/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChromeExtensionRouteImport } from './routes/chrome-extension'
import { Route as BrandKitRouteImport } from './routes/brand-kit'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as VsStagehandRouteImport } from './routes/vs/stagehand'
import { Route as VsPlaywrightCodegenRouteImport } from './routes/vs/playwright-codegen'
import { Route as VsBrowserUseRouteImport } from './routes/vs/browser-use'
import { Route as DashboardPrAgentRouteImport } from './routes/dashboard_.pr-agent'
import { Route as DashboardCloudBrowsersRouteImport } from './routes/dashboard_.cloud-browsers'
import { Route as DashboardChromeExtensionRouteImport } from './routes/dashboard_.chrome-extension'
import { Route as DashboardSectionRouteImport } from './routes/dashboard_.$section'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChromeExtensionRoute = ChromeExtensionRouteImport.update({
  id: '/chrome-extension',
  path: '/chrome-extension',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandKitRoute = BrandKitRouteImport.update({
  id: '/brand-kit',
  path: '/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const VsStagehandRoute = VsStagehandRouteImport.update({
  id: '/vs/stagehand',
  path: '/vs/stagehand',
  getParentRoute: () => rootRouteImport,
} as any)
const VsPlaywrightCodegenRoute = VsPlaywrightCodegenRouteImport.update({
  id: '/vs/playwright-codegen',
  path: '/vs/playwright-codegen',
  getParentRoute: () => rootRouteImport,
} as any)
const VsBrowserUseRoute = VsBrowserUseRouteImport.update({
  id: '/vs/browser-use',
  path: '/vs/browser-use',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPrAgentRoute = DashboardPrAgentRouteImport.update({
  id: '/dashboard_/pr-agent',
  path: '/dashboard/pr-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCloudBrowsersRoute = DashboardCloudBrowsersRouteImport.update({
  id: '/dashboard_/cloud-browsers',
  path: '/dashboard/cloud-browsers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChromeExtensionRoute =
  DashboardChromeExtensionRouteImport.update({
    id: '/dashboard_/chrome-extension',
    path: '/dashboard/chrome-extension',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/dashboard_/$section',
  path: '/dashboard/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/chrome-extension': typeof ChromeExtensionRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/dashboard/chrome-extension': typeof DashboardChromeExtensionRoute
  '/dashboard/cloud-browsers': typeof DashboardCloudBrowsersRoute
  '/dashboard/pr-agent': typeof DashboardPrAgentRoute
  '/vs/browser-use': typeof VsBrowserUseRoute
  '/vs/playwright-codegen': typeof VsPlaywrightCodegenRoute
  '/vs/stagehand': typeof VsStagehandRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-kit': typeof BrandKitRoute
  '/chrome-extension': typeof ChromeExtensionRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/dashboard/chrome-extension': typeof DashboardChromeExtensionRoute
  '/dashboard/cloud-browsers': typeof DashboardCloudBrowsersRoute
  '/dashboard/pr-agent': typeof DashboardPrAgentRoute
  '/vs/browser-use': typeof VsBrowserUseRoute
  '/vs/playwright-codegen': typeof VsPlaywrightCodegenRoute
  '/vs/stagehand': typeof VsStagehandRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/brand-kit': typeof BrandKitRoute
  '/chrome-extension': typeof ChromeExtensionRoute
  '/dashboard': typeof DashboardRoute
  '/invite': typeof InviteRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/verify-email': typeof VerifyEmailRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/dashboard_/$section': typeof DashboardSectionRoute
  '/dashboard_/chrome-extension': typeof DashboardChromeExtensionRoute
  '/dashboard_/cloud-browsers': typeof DashboardCloudBrowsersRoute
  '/dashboard_/pr-agent': typeof DashboardPrAgentRoute
  '/vs/browser-use': typeof VsBrowserUseRoute
  '/vs/playwright-codegen': typeof VsPlaywrightCodegenRoute
  '/vs/stagehand': typeof VsStagehandRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/brand-kit'
    | '/chrome-extension'
    | '/dashboard'
    | '/invite'
    | '/onboarding'
    | '/signin'
    | '/verify-email'
    | '/blog/$slug'
    | '/dashboard/$section'
    | '/dashboard/chrome-extension'
    | '/dashboard/cloud-browsers'
    | '/dashboard/pr-agent'
    | '/vs/browser-use'
    | '/vs/playwright-codegen'
    | '/vs/stagehand'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-kit'
    | '/chrome-extension'
    | '/dashboard'
    | '/invite'
    | '/onboarding'
    | '/signin'
    | '/verify-email'
    | '/blog/$slug'
    | '/dashboard/$section'
    | '/dashboard/chrome-extension'
    | '/dashboard/cloud-browsers'
    | '/dashboard/pr-agent'
    | '/vs/browser-use'
    | '/vs/playwright-codegen'
    | '/vs/stagehand'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/brand-kit'
    | '/chrome-extension'
    | '/dashboard'
    | '/invite'
    | '/onboarding'
    | '/signin'
    | '/verify-email'
    | '/blog/$slug'
    | '/dashboard_/$section'
    | '/dashboard_/chrome-extension'
    | '/dashboard_/cloud-browsers'
    | '/dashboard_/pr-agent'
    | '/vs/browser-use'
    | '/vs/playwright-codegen'
    | '/vs/stagehand'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  BrandKitRoute: typeof BrandKitRoute
  ChromeExtensionRoute: typeof ChromeExtensionRoute
  DashboardRoute: typeof DashboardRoute
  InviteRoute: typeof InviteRoute
  OnboardingRoute: typeof OnboardingRoute
  SigninRoute: typeof SigninRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardChromeExtensionRoute: typeof DashboardChromeExtensionRoute
  DashboardCloudBrowsersRoute: typeof DashboardCloudBrowsersRoute
  DashboardPrAgentRoute: typeof DashboardPrAgentRoute
  VsBrowserUseRoute: typeof VsBrowserUseRoute
  VsPlaywrightCodegenRoute: typeof VsPlaywrightCodegenRoute
  VsStagehandRoute: typeof VsStagehandRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chrome-extension': {
      id: '/chrome-extension'
      path: '/chrome-extension'
      fullPath: '/chrome-extension'
      preLoaderRoute: typeof ChromeExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-kit': {
      id: '/brand-kit'
      path: '/brand-kit'
      fullPath: '/brand-kit'
      preLoaderRoute: typeof BrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/vs/stagehand': {
      id: '/vs/stagehand'
      path: '/vs/stagehand'
      fullPath: '/vs/stagehand'
      preLoaderRoute: typeof VsStagehandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/playwright-codegen': {
      id: '/vs/playwright-codegen'
      path: '/vs/playwright-codegen'
      fullPath: '/vs/playwright-codegen'
      preLoaderRoute: typeof VsPlaywrightCodegenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/browser-use': {
      id: '/vs/browser-use'
      path: '/vs/browser-use'
      fullPath: '/vs/browser-use'
      preLoaderRoute: typeof VsBrowserUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/pr-agent': {
      id: '/dashboard_/pr-agent'
      path: '/dashboard/pr-agent'
      fullPath: '/dashboard/pr-agent'
      preLoaderRoute: typeof DashboardPrAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/cloud-browsers': {
      id: '/dashboard_/cloud-browsers'
      path: '/dashboard/cloud-browsers'
      fullPath: '/dashboard/cloud-browsers'
      preLoaderRoute: typeof DashboardCloudBrowsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/chrome-extension': {
      id: '/dashboard_/chrome-extension'
      path: '/dashboard/chrome-extension'
      fullPath: '/dashboard/chrome-extension'
      preLoaderRoute: typeof DashboardChromeExtensionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/$section': {
      id: '/dashboard_/$section'
      path: '/dashboard/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  BrandKitRoute: BrandKitRoute,
  ChromeExtensionRoute: ChromeExtensionRoute,
  DashboardRoute: DashboardRoute,
  InviteRoute: InviteRoute,
  OnboardingRoute: OnboardingRoute,
  SigninRoute: SigninRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardChromeExtensionRoute: DashboardChromeExtensionRoute,
  DashboardCloudBrowsersRoute: DashboardCloudBrowsersRoute,
  DashboardPrAgentRoute: DashboardPrAgentRoute,
  VsBrowserUseRoute: VsBrowserUseRoute,
  VsPlaywrightCodegenRoute: VsPlaywrightCodegenRoute,
  VsStagehandRoute: VsStagehandRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
