// This is an example workflow generated by create-libretto.
// Feel free to modify or delete it entirely and create your own workflows.

import { workflow } from "libretto";
import { log } from "../shared/utils.js";

export default workflow("star-repo", {
  startUrl: "https://github.com/saffron-health/libretto",
  handler: async ({ page }) => {
    log("Reading Libretto repo...");

    const description = await page
      .locator('meta[name="description"]')
      .getAttribute("content");
    log(`Repo description: ${description}`);

    const stars = await page.locator("#repo-stars-counter-star").textContent();
    log(`Stars: ${stars?.trim()}`);

    log("Done! Edit this workflow or create your own in src/workflows/.");
  },
});
