steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --platform
      - linux/amd64
      - -f
      - evals/Dockerfile
      - -t
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
